remote_theme: poole/hyde

# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: ShiroEE
tagline: 'ShiroEE Project'
description: ''
url: http://arthurgregorio.eti.br/shiro-ee
baseurl: /

author:
  name: 'Arthur Gregorio'
  url: https://twitter.com/gregorioarthur

paginate: 5

# Custom vars
version: 1.0.0

github:
  repo: https://github.com/arthurgregorio/shiro-ee

theme: jekyll-theme-cayman